# Generated by Django 2.1.1 on 2018-09-21 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_document_filepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='filepath',
        ),
    ]
