# Generated by Django 2.1.1 on 2018-09-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_document_filepath'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of scheme', max_length=200)),
                ('documents', models.ManyToManyField(to='website.Document')),
            ],
        ),
    ]
