# Generated by Django 2.1.1 on 2018-09-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(help_text='first name', max_length=200)),
                ('lname', models.CharField(help_text='last name', max_length=200)),
                ('email', models.CharField(help_text='email', max_length=200)),
                ('password', models.CharField(help_text='password', max_length=200)),
                ('mobile', models.CharField(help_text='mobile', max_length=200)),
            ],
        ),
    ]
